version: '3.3'

services:
  springboot-app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/flickhat
      SPRING_DATASOURCE_USERNAME: maxvpire
      SPRING_DATASOURCE_PASSWORD: max26156
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - app-network

  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5444:5432"
    environment:
      POSTGRES_DB: flickhat
      POSTGRES_USER: maxvpire
      POSTGRES_PASSWORD: max26156
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network: