services:
  postgres:
    container_name: flickhat-postgres
    image: postgres
    environment:
      POSTGRES_USER: maxvpire
      POSTGRES_PASSWORD: max26156
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: flickhat
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-flickhat
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local