spring:
  profiles:
    active: test

  mail:
    host: smtp.gmail.com
    port: 587
    username: maxvpire@gmail.com
    password: uxwz eidq zzyt zqtr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


server:
  servlet:
    context-path: /api/v1/
